cc_test(
    name = "goldens_test",
    srcs = ["goldens_test.cc"],
    data = ["//testdata"],
    deps = [
        "//lex",
        "//util",
        "//util:status_test",
        "@com_google_googletest//:gtest_main",
    ],
)
