cc_test(
    name = "goldens_test",
    srcs = ["goldens_test.cc"],
    data = ["//testdata"],
    deps = [
        "//cxm/lex",
        "//cxm/parse",
        "//cxm/util",
        "//cxm/util:status-test",
        "@com_google_googletest//:gtest_main",
    ],
)
