cc_binary(
    name = "main",
    srcs = ["main.cc"],
)

cc_test(
    name = "foo_test",
    srcs = [
        "foo_test.cc",
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)
